// Copy Variation Generator
//
// Produces 3 deterministic mock copy variations for a given ad.
// Variations are generated by applying three distinct messaging strategies:
//   1. Outcome-led   — lead with the end result the customer wants
//   2. Problem-first — name the pain before introducing the solution
//   3. Social proof  — open with credibility / community signal
//
// This is intentionally placeholder logic. When a real LLM integration is
// added, this file's exported function signature stays the same — only the
// body changes. The UI layer imports only `generateCopyVariations`.

import type { CopyVariation, CreativeDiagnosisInput } from "../types/creativeDiagnosis";

// ── Strategy templates ────────────────────────────────────────────────────────
// Each template is a function that receives context derived from the input
// and returns a CopyVariation. Keeping them as small named functions makes
// it easy to add / remove strategies without touching the orchestrator.

function outcomeLeadVariation(
  id: string,
  adName: string,
  cpaGoal: number
): CopyVariation {
  return {
    id,
    title:        "Variation A — Outcome-Led Hook",
    hook:         `What would you do with $${Math.round(cpaGoal * 0.6)} per conversion instead of wasting twice that?`,
    body:         "Most campaigns bleed budget because the message never speaks to the real outcome people want. We built a system that does exactly that — and the numbers show it. Join 14,000+ advertisers who cut CPA while growing revenue.",
    callToAction: "See The Strategy"
  };
}

function problemFirstVariation(
  id: string,
  adName: string
): CopyVariation {
  return {
    id,
    title:        "Variation B — Problem-First Hook",
    hook:         "Your ad is running. Your budget is spending. So why are conversions still flat?",
    body:         "It's almost never the targeting. In 80% of cases we've audited, the real problem is the message itself — the hook, the proof, the offer framing. This 3-step framework diagnoses the root cause in under 10 minutes.",
    callToAction: "Diagnose My Ad Now"
  };
}

function socialProofVariation(
  id: string,
  adName: string
): CopyVariation {
  return {
    id,
    title:        "Variation C — Social Proof Hook",
    hook:         "\"I was ready to pause this campaign. Then one copy change dropped CPA by 38% in 72 hours.\"",
    body:         "Sarah ran the same offer for 6 weeks with mediocre results. After testing a single hook variation using this framework, her ROAS jumped from 1.8× to 3.1× — same audience, same creative, different message. Here's the exact approach she used.",
    callToAction: "Get The Exact Framework"
  };
}

// ── Public API ────────────────────────────────────────────────────────────────

// NOTE: This is a MOCK generator — no LLM is called.
// The content is realistic placeholder copy that demonstrates the variation
// structure a real AI would fill in. Replace the body of this function with
// an API call (e.g. OpenAI chat completion) when ready.
export function generateCopyVariations(
  input: CreativeDiagnosisInput
): CopyVariation[] {
  const baseId = `copy_var_${input.adId}`;
  return [
    outcomeLeadVariation(`${baseId}_a`,   input.adName, input.cpaGoalValue),
    problemFirstVariation(`${baseId}_b`,  input.adName),
    socialProofVariation(`${baseId}_c`,   input.adName)
  ];
}
